name: Build-windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : Install
    - run : sudo apt install make
    - name: make
      run: make Run -c /3_IMPLEMENTATION ./gradingsystem.out
