name: Build-linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gcc gradingsystem.c -o gradingsystem.out
    - name: Run
      Run: ./gradingsystem.out
